[package]
name = "encodings"
version = "0.0.1"
authors = ["Urkel Labs Engineering <engineering@urkellabs.com>"]
edition = "2018"
license = "MIT"
description = "A crate containing common encoding styles"

[dependencies]
